export const CHANGE_ARTICLE_TITLE = 'CHANGE_ARTICLE_TITLE'
export const CHANGE_TYPE_NAME = 'CHANGE_TYPE_NAME'
export const CHANGE_ARTICLE_DETIALED = 'CHANGE_ARTICLE_DETIALED'
export const CHANGE_ABOUT = 'CHANGE_ABOUT'